### ISSUE TITLE
UnboundLocalError: local variable 'selected_index' referenced before assignment

### ISSUE THREAD

**Issue by MARYDS** [ctuning/ck-quantum#1]
```
Marys-MacBook-Pro:~ mary$ ck time_to_solution vqe --delta=0.015 --prob=0.95
 0) local:experiment:mary-2018_10_06T11_27_34-local_qasm_simulator-ansatz.universal4-optimizer.cobyla-samples.100-start.random-repetitions.1

Since there is only one option, auto-selecting it
Traceback (most recent call last):
  File "/Users/mary/anaconda/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/mary/anaconda/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/mary/anaconda/lib/python3.4/site-packages/ck/kernel.py", line 9611, in <module>
    r=access(sys.argv[1:])
  File "/Users/mary/anaconda/lib/python3.4/site-packages/ck/kernel.py", line 9567, in access
    rr=perform_action(i)
  File "/Users/mary/anaconda/lib/python3.4/site-packages/ck/kernel.py", line 3457, in perform_action
    return a(i)
  File "/Users/mary/CK/ck-quantum/module/vqe/module.py", line 518, in time_to_solution
    r=ck.access( {'action': 'pick_an_experiment', 'module_uoa': 'vqe'} )
  File "/Users/mary/anaconda/lib/python3.4/site-packages/ck/kernel.py", line 9567, in access
    rr=perform_action(i)
  File "/Users/mary/anaconda/lib/python3.4/site-packages/ck/kernel.py", line 3457, in perform_action
    return a(i)
  File "/Users/mary/CK/ck-quantum/module/vqe/module.py", line 436, in pick_an_experiment
    r=ck.access( select_adict )
  File "/Users/mary/anaconda/lib/python3.4/site-packages/ck/kernel.py", line 9567, in access
    rr=perform_action(i)
  File "/Users/mary/anaconda/lib/python3.4/site-packages/ck/kernel.py", line 3457, in perform_action
    return a(i)
  File "/Users/mary/CK/ck-env/module/misc/module.py", line 558, in select_string
    selected_value = options[selected_index][0] if selected_index >= 0 else ''
UnboundLocalError: local variable 'selected_index' referenced before assignment
```

**Comment by ens-lg4** [comment]
I believe I have fixed it during the hackathon.

If you can still reproduce it with up-to-date code, please reopen the ticket.
Thanks!
